version: "3.8"
services:
  mealpedant_backup_server:
    image: mealpedant_backup_server:0.1.9
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mealpedant_backup_server
    volumes:
      - /srv/backup/mealpedant:/backups:ro
      - $HOME/mealpedant_backup/.env:/app_env/.env:ro
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    ipc: private
    restart: always
    networks:
      - mealpedant_backup_server-net
    logging:
      options:
        max-size: 10m
    deploy:
      resources:
        limits:
          memory: 16M
networks:
  mealpedant_backup_server-net:
    name: mealpedant_backup_server-net
