name: Release CI
on:
  push:
    tags: 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      ####################################
      ## Build binaries for release page #
      ####################################
      
      # Install stable rust, and associated tools
      - name: install rust
        uses: dtolnay/rust-toolchain@stable

      # Install cross-rs
      - name: install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      # Build for linux x86 musl, aka alpine container
      - name: build x86_64-unknown-linux-musl
        run: cross build --target x86_64-unknown-linux-musl --release

      # Compress ouput into tar
      - name: compress armv6 binary
        run: tar -C target/x86_64-unknown-linux-musl/release -czf ./mealpedant_backup_server_linux_x86_musl.tar.gz mealpedant_backup_server
      
      ###################
      ## Create release #
      ###################

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          body_path: ".github/release-body.md"
          draft: false
          files: |
            mealpedant_backup_server_linux_x86_musl.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
